# BLDC Board Support Package — CMake integration
#
# Usage (from a firmware CMakeLists.txt):
#   set(BLDC_BSP_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../shared/bsp)
#   include(${BLDC_BSP_DIR}/cmake/bldc_bsp.cmake)
#   bldc_bsp_configure(TARGET ${CMAKE_PROJECT_NAME})
#
# Select board:
#   cmake -DBLDC_BOARD=stm32g431 ..
#   cmake -DBLDC_BOARD=stm32f411 ..

set(BLDC_BOARD "stm32g431" CACHE STRING "BLDC target board (see shared/bsp/boards/)")
set_property(CACHE BLDC_BOARD PROPERTY STRINGS stm32g431 stm32f411)

function(bldc_bsp_parse_conf conf_file out_vars)
    if(NOT EXISTS "${conf_file}")
        message(FATAL_ERROR "BLDC BSP: board.conf not found: ${conf_file}")
    endif()

    file(READ "${conf_file}" _conf_raw)
    string(REPLACE "\r\n" "\n" _conf_raw "${_conf_raw}")
    string(REPLACE "\r" "\n" _conf_raw "${_conf_raw}")
    string(REGEX MATCHALL "[^\n]+" _conf_lines "${_conf_raw}")

    set(_vars "")
    foreach(_line IN LISTS _conf_lines)
        string(STRIP "${_line}" _line)
        if(_line STREQUAL "" OR _line MATCHES "^#")
            continue()
        endif()

        if(_line MATCHES "^CONFIG_([A-Za-z0-9_]+)=\"(.*)\"$")
            set(_key "CONFIG_${CMAKE_MATCH_1}")
            set(_val "\"${CMAKE_MATCH_2}\"")
            list(APPEND _vars "${_key}=${_val}")
        elseif(_line MATCHES "^CONFIG_([A-Za-z0-9_]+)=(y|n|[0-9]+)$")
            set(_key "CONFIG_${CMAKE_MATCH_1}")
            set(_raw "${CMAKE_MATCH_2}")
            if(_raw STREQUAL "y")
                set(_val "1")
            elseif(_raw STREQUAL "n")
                set(_val "0")
            else()
                set(_val "${_raw}")
            endif()
            list(APPEND _vars "${_key}=${_val}")
        else()
            message(WARNING "BLDC BSP: skipping unrecognized line in ${conf_file}: ${_line}")
        endif()
    endforeach()

    set(${out_vars} "${_vars}" PARENT_SCOPE)
endfunction()

function(bldc_bsp_generate_autoconf conf_vars output_header)
    set(_header "/* Auto-generated by bldc_bsp.cmake — do not edit */\n")
    string(APPEND _header "#ifndef BLDC_BSP_AUTOCONF_H\n#define BLDC_BSP_AUTOCONF_H\n\n")

    set(_family "")
    foreach(_entry IN LISTS conf_vars)
        string(REPLACE "=" ";" _parts "${_entry}")
        list(GET _parts 0 _key)
        list(GET _parts 1 _val)
        string(APPEND _header "#define ${_key} ${_val}\n")
        if(_key STREQUAL "CONFIG_STM32_FAMILY")
            string(REGEX REPLACE "^\"(.*)\"$" "\\1" _family "${_val}")
        endif()
    endforeach()

    if(_family STREQUAL "G4")
        string(APPEND _header "\n#define CONFIG_STM32_FAMILY_G4 1\n")
    elseif(_family STREQUAL "F4")
        string(APPEND _header "\n#define CONFIG_STM32_FAMILY_F4 1\n")
    else()
        message(FATAL_ERROR "BLDC BSP: unknown CONFIG_STM32_FAMILY '${_family}'")
    endif()

    string(APPEND _header "\n/* Kconfig aliases for portable bldc/ code */\n")
    string(APPEND _header "#define BLDC_COMPLEMENTARY_DRIVE CONFIG_BLDC_COMPLEMENTARY_DRIVE\n")
    string(APPEND _header "#define BLDC_TELEM_USE_DEMO CONFIG_BLDC_TELEM_USE_DEMO\n")
    string(APPEND _header "#define ADC_CHANNEL_COUNT CONFIG_BLDC_ADC_DMA_CHANNELS\n\n")
    string(APPEND _header "#endif /* BLDC_BSP_AUTOCONF_H */\n")

    file(WRITE "${output_header}" "${_header}")
endfunction()

function(bldc_bsp_configure)
    set(options)
    set(oneValueArgs TARGET)
    set(multiValueArgs)
    cmake_parse_arguments(BSP "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(NOT BSP_TARGET)
        message(FATAL_ERROR "bldc_bsp_configure(TARGET <name> ...) requires TARGET")
    endif()

    set(_board_dir "${BLDC_BSP_DIR}/boards/${BLDC_BOARD}")
    set(_conf_file "${_board_dir}/board.conf")

    bldc_bsp_parse_conf("${_conf_file}" _conf_vars)
    message(STATUS "BLDC BSP: board=${BLDC_BOARD}")

    set(_gen_dir "${CMAKE_BINARY_DIR}/generated")
    file(MAKE_DIRECTORY "${_gen_dir}")
    set(_autoconf "${_gen_dir}/bsp_autoconf.h")
    bldc_bsp_generate_autoconf("${_conf_vars}" "${_autoconf}")

    target_include_directories(${BSP_TARGET} PRIVATE
        "${BLDC_BSP_DIR}"
        "${_board_dir}"
        "${_gen_dir}"
    )

    set(_board_sources
        "${BLDC_BSP_DIR}/bsp.c"
        "${_board_dir}/board.c"
    )

    set(_bldc_sources
        "${BLDC_BSP_DIR}/bsp_math.c"
        "${BLDC_BSP_DIR}/commutation.c"
        "${BLDC_BSP_DIR}/telem.c"
        "${BLDC_BSP_DIR}/utils.c"
    )

    set(_has_drv8323 0)
    set(_has_dronecan 0)
    set(_has_usb_telem 0)
    set(_has_hw_accel 0)

    foreach(_entry IN LISTS _conf_vars)
        string(REPLACE "=" ";" _parts "${_entry}")
        list(GET _parts 0 _key)
        list(GET _parts 1 _val)
        if(_key STREQUAL "CONFIG_BLDC_HAS_DRV8323" AND _val STREQUAL "1")
            set(_has_drv8323 1)
        endif()
        if(_key STREQUAL "CONFIG_BLDC_HAS_DRONECAN" AND _val STREQUAL "1")
            set(_has_dronecan 1)
        endif()
        if(_key STREQUAL "CONFIG_BLDC_HAS_USB_TELEM" AND _val STREQUAL "1")
            set(_has_usb_telem 1)
        endif()
        if(_key STREQUAL "CONFIG_BLDC_HAS_HW_ACCEL" AND _val STREQUAL "1")
            set(_has_hw_accel 1)
        endif()
    endforeach()

    if(_has_hw_accel)
        list(APPEND _board_sources "${_board_dir}/hw_accel.c")
    endif()

    target_sources(${BSP_TARGET} PRIVATE ${_board_sources})

    if(_has_drv8323)
        list(APPEND _bldc_sources "${BLDC_BSP_DIR}/drv8323r.c")
    endif()
    if(_has_dronecan)
        list(APPEND _bldc_sources "${BLDC_BSP_DIR}/dronecan.c")
    endif()
    if(_has_usb_telem)
        list(APPEND _bldc_sources "${BLDC_BSP_DIR}/usb.c")
    endif()

    target_sources(${BSP_TARGET} PRIVATE ${_bldc_sources})

    set_source_files_properties(
        ${_board_sources}
        ${_bldc_sources}
        PROPERTIES COMPILE_OPTIONS -O3;-Wall;-Wextra
    )

    if(_has_usb_telem)
        target_include_directories(${BSP_TARGET} PRIVATE
            "${CMAKE_SOURCE_DIR}/Middlewares/Third_Party/NanoCBOR/include"
        )
        target_sources(${BSP_TARGET} PRIVATE
            "${CMAKE_SOURCE_DIR}/Middlewares/Third_Party/NanoCBOR/src/decoder.c"
            "${CMAKE_SOURCE_DIR}/Middlewares/Third_Party/NanoCBOR/src/encoder.c"
        )
        set_source_files_properties(
            "${CMAKE_SOURCE_DIR}/Middlewares/Third_Party/NanoCBOR/src/decoder.c"
            "${CMAKE_SOURCE_DIR}/Middlewares/Third_Party/NanoCBOR/src/encoder.c"
            PROPERTIES COMPILE_OPTIONS -w
        )
    endif()

    if(_has_dronecan)
        file(GLOB _dsdl_sources CONFIGURE_DEPENDS
            "${CMAKE_SOURCE_DIR}/Middlewares/Third_Party/dsdl_generated/src/*.c"
        )
        if(NOT _dsdl_sources)
            message(FATAL_ERROR
                "BLDC BSP: DroneCAN enabled but no DSDL sources found. "
                "Run 'make dsdl_gen_build' in ${CMAKE_SOURCE_DIR} first.")
        endif()

        target_include_directories(${BSP_TARGET} PRIVATE
            "${CMAKE_SOURCE_DIR}/Middlewares/Third_Party/libcanard"
            "${CMAKE_SOURCE_DIR}/Middlewares/Third_Party/dsdl_generated/include"
        )
        target_sources(${BSP_TARGET} PRIVATE
            ${_dsdl_sources}
            "${CMAKE_SOURCE_DIR}/Middlewares/Third_Party/libcanard/canard.c"
        )
        set_source_files_properties(
            ${_dsdl_sources}
            "${CMAKE_SOURCE_DIR}/Middlewares/Third_Party/libcanard/canard.c"
            PROPERTIES COMPILE_OPTIONS -w
        )
    endif()

    file(GLOB _core_sources CONFIGURE_DEPENDS
        "${CMAKE_SOURCE_DIR}/Core/Src/*.c"
    )
    if(_core_sources)
        set_source_files_properties(${_core_sources} PROPERTIES
            COMPILE_OPTIONS
                -O3;-Wall;-Wextra;-Wformat=2;-Wno-unused-parameter;-Wshadow;-Wwrite-strings;-Wold-style-definition;-Wmissing-include-dirs
        )
    endif()
endfunction()