/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.2 */

#ifndef PB_BLDC_PROTOCOL_BLDC_PB_H_INCLUDED
#define PB_BLDC_PROTOCOL_BLDC_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Telemetry values use fixed engineering units so the firmware neither needs
 floating point nor loses precision on the wire. */
typedef struct _bldc_Telemetry {
    /* The protocol version of the telemetry message. */
    uint32_t protocol_version;
    uint32_t sequence;
    /* Uptime in milliseconds since the device was powered on. */
    uint32_t uptime_ms;
    /* Measured bus voltage (VM) in millivolts. */
    uint32_t bus_voltage_mv;
    /* NTC_PCB temperature in 0.1(1sf) degrees C; INT32_MIN means invalid ADC input. */
    int32_t ntc_pcb_temperature_cdec;
    /* Measured phase currents in milliamps. Signed: the DRV8323 CSAs run
 bidirectionally with SOx biased at VREF/2, so zero current is mid-rail
 and reverse current is negative. */
    int32_t curr_a_ma;
    int32_t curr_b_ma;
    int32_t curr_c_ma;
    /* Measured phase voltages in millivolts. */
    uint32_t volt_a_mv;
    uint32_t volt_b_mv;
    uint32_t volt_c_mv;
} bldc_Telemetry;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define bldc_Telemetry_init_default              {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define bldc_Telemetry_init_zero                 {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define bldc_Telemetry_protocol_version_tag      1
#define bldc_Telemetry_sequence_tag              2
#define bldc_Telemetry_uptime_ms_tag             3
#define bldc_Telemetry_bus_voltage_mv_tag        4
#define bldc_Telemetry_ntc_pcb_temperature_cdec_tag 8
#define bldc_Telemetry_curr_a_ma_tag             9
#define bldc_Telemetry_curr_b_ma_tag             10
#define bldc_Telemetry_curr_c_ma_tag             11
#define bldc_Telemetry_volt_a_mv_tag             12
#define bldc_Telemetry_volt_b_mv_tag             13
#define bldc_Telemetry_volt_c_mv_tag             14

/* Struct field encoding specification for nanopb */
#define bldc_Telemetry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   protocol_version,   1) \
X(a, STATIC,   SINGULAR, UINT32,   sequence,          2) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_ms,         3) \
X(a, STATIC,   SINGULAR, UINT32,   bus_voltage_mv,    4) \
X(a, STATIC,   SINGULAR, SINT32,   ntc_pcb_temperature_cdec,   8) \
X(a, STATIC,   SINGULAR, SINT32,   curr_a_ma,         9) \
X(a, STATIC,   SINGULAR, SINT32,   curr_b_ma,        10) \
X(a, STATIC,   SINGULAR, SINT32,   curr_c_ma,        11) \
X(a, STATIC,   SINGULAR, UINT32,   volt_a_mv,        12) \
X(a, STATIC,   SINGULAR, UINT32,   volt_b_mv,        13) \
X(a, STATIC,   SINGULAR, UINT32,   volt_c_mv,        14)
#define bldc_Telemetry_CALLBACK NULL
#define bldc_Telemetry_DEFAULT NULL

extern const pb_msgdesc_t bldc_Telemetry_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define bldc_Telemetry_fields &bldc_Telemetry_msg

/* Maximum encoded size of messages (where known) */
#define BLDC_PROTOCOL_BLDC_PB_H_MAX_SIZE         bldc_Telemetry_size
#define bldc_Telemetry_size                      66

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
